## Path to sample sheet
samplesheet: 'samplesheet.txt'

## List columns to concatenate for file names 
## (or indicate a single Name column, i.e. fileNamesFrom: ['Name'])
fileNamesFrom: ['Project', 'Cell_Type', 'Genotype', 'Time', 'Bio_Rep', 'Tech_Rep']

## List columns to group (i.e. any columns left out will become part of the same group)
mergeBy: ['Project', 'Cell_Type', 'Genotype', 'Time', 'Bio_Rep', 'Tech_Rep']

## Genome-specific reference parameters
fasta: '/proj/seq/data/HG19_UCSC/Sequence/BWAIndex/genome.fa' 
chromSizes: '/proj/phanstiel_lab/References/chromSizes/hg19_chromSizes.txt'
